/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as AuthenticatedBranchesRouteImport } from "./routes/_authenticated/branches";
import { Route as AuthenticatedAssignedBranchRouteImport } from "./routes/_authenticated/_assignedBranch";
import { Route as AuthenticatedAssignedBranchLoansRouteImport } from "./routes/_authenticated/_assignedBranch.loans";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: "/branches",
  path: "/branches",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedAssignedBranchRoute =
  AuthenticatedAssignedBranchRouteImport.update({
    id: "/_assignedBranch",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedAssignedBranchLoansRoute =
  AuthenticatedAssignedBranchLoansRouteImport.update({
    id: "/loans",
    path: "/loans",
    getParentRoute: () => AuthenticatedAssignedBranchRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedAssignedBranchRouteWithChildren;
  "/login": typeof LoginRoute;
  "/branches": typeof AuthenticatedBranchesRoute;
  "/loans": typeof AuthenticatedAssignedBranchLoansRoute;
}
export interface FileRoutesByTo {
  "/": typeof AuthenticatedAssignedBranchRouteWithChildren;
  "/login": typeof LoginRoute;
  "/branches": typeof AuthenticatedBranchesRoute;
  "/loans": typeof AuthenticatedAssignedBranchLoansRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_authenticated/_assignedBranch": typeof AuthenticatedAssignedBranchRouteWithChildren;
  "/_authenticated/branches": typeof AuthenticatedBranchesRoute;
  "/_authenticated/_assignedBranch/loans": typeof AuthenticatedAssignedBranchLoansRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/branches" | "/loans";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/login" | "/branches" | "/loans";
  id:
    | "__root__"
    | "/_authenticated"
    | "/login"
    | "/_authenticated/_assignedBranch"
    | "/_authenticated/branches"
    | "/_authenticated/_assignedBranch/loans";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/branches": {
      id: "/_authenticated/branches";
      path: "/branches";
      fullPath: "/branches";
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/_assignedBranch": {
      id: "/_authenticated/_assignedBranch";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedAssignedBranchRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/_assignedBranch/loans": {
      id: "/_authenticated/_assignedBranch/loans";
      path: "/loans";
      fullPath: "/loans";
      preLoaderRoute: typeof AuthenticatedAssignedBranchLoansRouteImport;
      parentRoute: typeof AuthenticatedAssignedBranchRoute;
    };
  }
}

interface AuthenticatedAssignedBranchRouteChildren {
  AuthenticatedAssignedBranchLoansRoute: typeof AuthenticatedAssignedBranchLoansRoute;
}

const AuthenticatedAssignedBranchRouteChildren: AuthenticatedAssignedBranchRouteChildren =
  {
    AuthenticatedAssignedBranchLoansRoute:
      AuthenticatedAssignedBranchLoansRoute,
  };

const AuthenticatedAssignedBranchRouteWithChildren =
  AuthenticatedAssignedBranchRoute._addFileChildren(
    AuthenticatedAssignedBranchRouteChildren,
  );

interface AuthenticatedRouteChildren {
  AuthenticatedAssignedBranchRoute: typeof AuthenticatedAssignedBranchRouteWithChildren;
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssignedBranchRoute:
    AuthenticatedAssignedBranchRouteWithChildren,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
